eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8277
spring:
  application:
    name: HR-Service
  boot:
    client:
      admin:
        url: http://localhost:8888
  datasource:
    password: Komal06@#10
    url: jdbc:mysql://localhost:3306/project
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
