server:
   port: 0
spring:
     application:
          name: feign-service
     datasource:
          url: jdbc:mysql://localhost:3306/project
          username: root
          password: Komal06@#10
     jpa:
        hibernate:
          ddl-auto: create
     boot:
       admin:
          client:
           url: http://localhost:8888
     main:
       allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
logging:
  file:
    name: feign-service.log
