server:
  port: 9999
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
 
    config:
      uri:
      - http://localhost:9090
      enabled: false
  boot:
    admin:
      client:
        url:
        - http://localhost:8888